#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnuchess
Version  : 6.2.5
Release  : 1
URL      : https://ftp.gnu.org/gnu/chess/gnuchess-6.2.5.tar.gz
Source0  : https://ftp.gnu.org/gnu/chess/gnuchess-6.2.5.tar.gz
Summary  : Play chess against the computer on a terminal and an engine for graphical chess frontends
Group    : Development/Tools
License  : GPL-3.0
Requires: gnuchess-bin = %{version}-%{release}
Requires: gnuchess-data = %{version}-%{release}
Requires: gnuchess-license = %{version}-%{release}
Requires: gnuchess-locales = %{version}-%{release}
Requires: gnuchess-man = %{version}-%{release}
BuildRequires : flex
BuildRequires : ncurses-dev
BuildRequires : readline-dev

%description
GNU Chess Project
For latest information visit:
http://www.gnu.org/software/chess/

%package bin
Summary: bin components for the gnuchess package.
Group: Binaries
Requires: gnuchess-data = %{version}-%{release}
Requires: gnuchess-license = %{version}-%{release}

%description bin
bin components for the gnuchess package.


%package data
Summary: data components for the gnuchess package.
Group: Data

%description data
data components for the gnuchess package.


%package doc
Summary: doc components for the gnuchess package.
Group: Documentation
Requires: gnuchess-man = %{version}-%{release}

%description doc
doc components for the gnuchess package.


%package license
Summary: license components for the gnuchess package.
Group: Default

%description license
license components for the gnuchess package.


%package locales
Summary: locales components for the gnuchess package.
Group: Default

%description locales
locales components for the gnuchess package.


%package man
Summary: man components for the gnuchess package.
Group: Default

%description man
man components for the gnuchess package.


%prep
%setup -q -n gnuchess-6.2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566316658
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1566316658
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnuchess
cp COPYING %{buildroot}/usr/share/package-licenses/gnuchess/COPYING
%make_install
%find_lang gnuchess

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnuchess
/usr/bin/gnuchessu
/usr/bin/gnuchessx

%files data
%defattr(-,root,root,-)
/usr/share/games/plugins/logos/gnuchess.png
/usr/share/games/plugins/xboard/gnuchess.eng
/usr/share/gnuchess/gnuchess.ini
/usr/share/gnuchess/smallbook.bin

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnuchess/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnuchess.1

%files locales -f gnuchess.lang
%defattr(-,root,root,-)

