#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v24
# autospec commit: a88ffdc
#
# Source0 file verified with key 0x43AC7FF93CED5A6B (aceballos@gmail.com)
#
Name     : gnuchess
Version  : 6.2.11
Release  : 13
URL      : https://mirrors.kernel.org/gnu/chess/gnuchess-6.2.11.tar.gz
Source0  : https://mirrors.kernel.org/gnu/chess/gnuchess-6.2.11.tar.gz
Source1  : https://mirrors.kernel.org/gnu/chess/gnuchess-6.2.11.tar.gz.sig
Source2  : 43AC7FF93CED5A6B.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: gnuchess-bin = %{version}-%{release}
Requires: gnuchess-data = %{version}-%{release}
Requires: gnuchess-info = %{version}-%{release}
Requires: gnuchess-license = %{version}-%{release}
Requires: gnuchess-locales = %{version}-%{release}
Requires: gnuchess-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : gnupg
BuildRequires : ncurses-dev
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
GNU Chess Project
For latest information visit:
http://www.gnu.org/software/chess/

%package bin
Summary: bin components for the gnuchess package.
Group: Binaries
Requires: gnuchess-data = %{version}-%{release}
Requires: gnuchess-license = %{version}-%{release}

%description bin
bin components for the gnuchess package.


%package data
Summary: data components for the gnuchess package.
Group: Data

%description data
data components for the gnuchess package.


%package info
Summary: info components for the gnuchess package.
Group: Default

%description info
info components for the gnuchess package.


%package license
Summary: license components for the gnuchess package.
Group: Default

%description license
license components for the gnuchess package.


%package locales
Summary: locales components for the gnuchess package.
Group: Default

%description locales
locales components for the gnuchess package.


%package man
Summary: man components for the gnuchess package.
Group: Default

%description man
man components for the gnuchess package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 43AC7FF93CED5A6B' gpg.status
%setup -q -n gnuchess-6.2.11
cd %{_builddir}/gnuchess-6.2.11
pushd ..
cp -a gnuchess-6.2.11 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745245664
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1745245664
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnuchess
cp %{_builddir}/gnuchess-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnuchess/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang gnuchess
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gnuchess
/usr/bin/gnuchess
/usr/bin/gnuchessu
/usr/bin/gnuchessx

%files data
%defattr(-,root,root,-)
/usr/share/games/plugins/logos/gnuchess.png
/usr/share/games/plugins/xboard/gnuchess.eng
/usr/share/gnuchess/gnuchess.ini
/usr/share/gnuchess/smallbook.bin

%files info
%defattr(0644,root,root,0755)
/usr/share/info/gnuchess.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnuchess/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnuchess.1

%files locales -f gnuchess.lang
%defattr(-,root,root,-)

